Feature/#700
AtlasOfLivingAustralia/profile-hub pull request #786
Opened 2023-09-19 23:27 UTC by schoicsiro

Would you be able to get PR?

2023-10-04 01:48 UTC, temi commented on grails-app/assets/javascripts/profileEditor/controllers/UserAccessController.js
> +                var promise = profileService.updateUsers(self.opusId, data);
refresh user list after update.

2023-10-05 03:58 UTC, schoicsiro commented on grails-app/assets/javascripts/profileEditor/controllers/UserAccessController.js
> +                var promise = profileService.updateUsers(self.opusId, data);
user list refreshing works after update

2023-10-06 00:36 UTC, temi requested changes

2023-10-06 00:36 UTC, temi commented on grails-app/assets/javascripts/profileEditor/controllers/UserAccessController.js
> +    self.privateModeChanged = function(form) {
This function is also called when opus is loaded. The user filtering and subsequent update should only run when user has clicked private collection button and not when opus is loaded.

2023-10-06 02:37 UTC, temi approved these changes

2023-10-06 02:45 UTC, merged